### ISSUE TITLE
Links for Testing Data

### ISSUE THREAD

**Issue by varadpoddar** [varadpoddar/MB-System#1]
Requesting repo links for test data.

**Comment by MBARIMike** [comment]
Some sample .grd files are available on our public STOQS server: https://stoqs.mbari.org/

Use a wget or curl command to get the file from:

https://stoqs.mbari.org/terrain/Monterey25.grd
https://stoqs.mbari.org/terrain/michigan_lld.grd
https://stoqs.mbari.org/terrain/Globe_1m_bath.grd

**Comment by varadpoddar** [comment]
Added those, and [Erie](https://stoqs.mbari.org/terrain/erie_lld.grd) to test-data folder. Added folder to .git-ignore. 
Closing the issue, will reopen for further testing data if needed.
