### ISSUE TITLE
Filter the draco folder files to only include the ones we need

### ISSUE THREAD

**Issue by varadpoddar** [varadpoddar/MB-System#2]
**Hinderance**
The current infrastructure is aimed at loading the [google/draco](https://github.com/google/draco) , [syoyo/tinygltf](https://github.com/syoyo/tinygltf) from static folders within the mbgrd2gltf folder. This makes it tedious to upgrade the dependencies.

**Prospective Solution**
We can use git [submodules](https://git-scm.com/docs/git-submodule) and [sparse-checkout](https://git-scm.com/docs/git-sparse-checkout) to make it programmatically easier to update these dependencies for current and future use.

**Alternatives**
Leave the current process alone and update dependencies as required.

**Tasks**

~~- [ ] Add git-submodule for draco~~
~~- [ ] sparse-checkout draco/src/draco/{attributes,compression,core,mesh,metadata,point_cloud,texture} Folders + draco_features.h + draco license~~
~~- [ ] Add git-submodule for tinyGLTF~~
~~- [ ] sparse-checkout specific files for tinyGLTF + license~~

Edit: 
We are going to stick with the same structure and drop in the required files. 
New tasks include :

- [ ] Remove unnecessary build files from the draco folder and ensure build.

**Comment by MBARIMike** [comment]
In the spirit of the MB-System project I think it's fine to leave the current process alone and update dependencies as required.

**Comment by varadpoddar** [comment]
Thanks @MBARIMike, 
I have updated the description.

@IvanMart57 Would you be able to take a look at this and see of you can filter through and remove the unnecessary files ?

Blue Pill : A simple way would be to remove the files and introduce them one by one based on the include errors. 

Red Pill : A sophisticated way would be to use a dependency checker utility that would be able to sniff out the dependencies for draco/encode.h and list the dependent files. 

Thank You

**Comment by varadpoddar** [comment]
This was partially fixed in commit 26c3858090eba1c2a4e44885b28a6ee212dd70c5 using BluePill method along with using built in Draco binaries if installed. Marking Closed.
